
project_id = "lecahcsrnyquowhmxwer"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[functions]
[functions.create-xumm-payment]
verify_jwt = true

[functions.check-xumm-payment]
verify_jwt = true

